config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :users, only: [:show, :update]
  
  resources :items

  get 'about' => 'welcome#about'

    root to: 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  def days_left
    (due_date - Date.today).to_i rescue "THE WORLD IS ENDING"
  end

  def self.active
    where(status: "Pending")    
  end

  def self.archived
    where(status: "Archived")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    items_path
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @user = current_user

    case params[:filter]
    when "archived"
      @items = Item.archived.where(user_id: @user.id)
      @item = Item.new
    else
      @items = Item.active.where(user_id: @user.id)
      @item = Item.new
    end
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id 
    if @item.save
      redirect_to items_path
      # render :index, notice: "Task was saved to your list."
    else
      flash[:error] = "Error creating task. Please try again."
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:notice] = "Task was updated"
      redirect_to items_path
    else
      flash[:error] = "There was an error saving your task. Please try again."
      render :show
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.status = "Archived"
    @item.save

    render js: "$('##{@item.id}').slideUp()"
  end

  private

    def item_params
      params.require(:item).permit(:user_id, :due_date, :description, :status)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @items = Item.where(user_id: @user.id)
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :avatar, :email_favorites)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for item, {url: items_path(item), html: {name: "item"}} do |f| %>
  <td class="items-row col-md-8 form-group">
    <%= f.text_field :description, form: "new_item", class: 'form-control', placeholder: "Enter task description" %>
  </td>
  <td class="items-row col-md-3 form-group">
    <%= f.date_field :due_date, form: "new_item", class: 'form-control' %>
  </td>
  <td colspan="2" class="items-row col-md-3 form-group">
    <%= f.submit "Save New Task", form: "new_item", class: 'btn btn-success btn-block' %>
  </td>
<% end %>

app/views/items/_item.html.erb
<tr class="items-table" id="<%= item.id %>">
  <td class="items-row col-md-8"><%= link_to "#{item.description}", item_path(item) %></td>
  <td class="items-row-center col-md-2"><%= item.status %></td>
  <td class="items-row-center col-md-1"><%= item.days_left %></td>
  <td class="col-md-1" style="text-align:center"><input type="checkbox" class="archive-button" data-id="<%=item.id%>"></input></td>
</tr>

app/views/items/edit.html.erb
<h1>Edit Task</h1>

<div>
  <div class="col-md-10">
    <%= form_for @item do |f| %>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control', placeholder: "Enter task description" %>
      </div>
      <div class="form-group">
        <%= f.label :due_date %>
        <%= f.date_field :due_date, class: 'form-control' %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<div class="row">
  <div>
    <h3>My List</h3>
  </div>
  <div class="pull-right button">
    <%= link_to "New Task", new_item_path, class: 'btn btn-success' %>
  </div>
</div> 

<div>
  <table style="width:100%" class="table-striped">
    <thead>
      <tr class="items-table">
        <th class="items-row col-md-6">Task Description</th>
        <th class="items-row-center col-md-2">Status</th>
        <th class="items-row-center col-md-2">Days Left</th>
        <th class="items-row col-md-2">Archive?</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "items/item", collection: @items %>
      <tr class="items-table">
        <%= render partial: "items/form", locals: { item: @item } %>
      </tr>
    </tbody>
  </table>
</div>


<script>
  var archiveItem = function(id){
    $.ajax("/items/"+id, {method: "DELETE"})
  }


  $(".archive-button").click(function(){
    archiveItem($(this).data('id'))
  })
</script>

app/views/items/new.html.erb
<h1>New Task</h1>

<div>
  <div class="col-md-10">
    <%= form_for @item do |f| %>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control', placeholder: "Enter task description" %>
      </div>
      <div class="form-group">
        <%= f.label :due_date %>
        <%= f.date_field :due_date, class: 'form-control' %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<h1>Task</h1>

<div>
  <div class="col-md-10">
    <%= form_for @item, method: "patch" do |f| %>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control', placeholder: "Enter task description" %>
      </div>
      <div class="form-group">
        <%= f.label :due_date %>
        <%= f.date_field :due_date, class: 'form-control' %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <ul class="nav nav-tabs">
      <li><%= link_to "Blocitoff", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if current_user.present? %>
        <li><%= link_to "My List", items_path %></li>
        <li><%= link_to "Archived", items_path(filter: "archived") %></li>
      <% end %>

      <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= link_to (current_user.name || current_user.email), current_user %>!
          <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-user"></span>
          <% end %>

          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-log-out">Sign Out</span>
          <% end %>

        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/users/show.html.erb
<h1>My Profile</h1>

<div>
  <table class="col-md-4">
    <tbody>
      <tr class="success">
        <td><strong>Active Tasks</strong></td>
        <td><%= link_to "#{@items.where(status: "Pending").count} tasks", items_path %></td>
      </tr>
      <tr class="info">
        <td><strong>Archived Tasks</strong></td>
        <td><%= link_to "#{@items.where(status: "Archived").count} tasks", items_path(filter: "archived") %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/welcome/about.html.erb
<h1>Welcome to Blocitoff</h1>
<p>A self destructing to-do list to keep you focused on the things that really matter.</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1 class="home">Blocitoff</h1>
  <p class="home">
    A self destructing to-do list to keep you focused on the things that really matter.
  </p>
  <p class="home">
    <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
  </p>
</div>